config/routes.rb
Rails.application.routes.draw do
  root "gyms#index"
  #get "/gyms", to: "gyms#index"
  #get "/gyms/:id", to:"gyms#show"
  resources :gyms do
    resources :barbells
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barbell.rb
class Barbell < ApplicationRecord
  belongs_to :gym

end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :barbells, dependent: :destroy
  accepts_nested_attributes_for :barbells, allow_destroy: true
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :logo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/barbells_controller.rb
class BarbellsController < ApplicationController

  def new
    @gym = Gym.find(params[:gym_id])
    @barbell = Barbell.new(barbell_params)
    redirect_to gym_path(@gym)
  end

   def create
    @gym = Gym.find(params[:gym_id])
    @barbell = @gym.barbells.create(barbell_params)
    redirect_to gym_path(@gym)
  end


  private
    def barbell_params
      params.require(:barbell).permit(:brand, :weight)
    end

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  def index
    @gyms = Gym.all
  end

  def show
   @gym = Gym.find(params[:id])
  end

  def new
    @gym = Gym.new
  end

  def create
    @gym = Gym.new(gym_params)

    if @gym.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @gym = Gym.find(params[:id])


  end

  def update
    @gym = Gym.find(params[:id])

    if @gym.update(gym_params)
      redirect_to @gym
    else
      render :edit
    end
  end

  def destroy
    @gym = Gym.find(params[:id])
    @gym.destroy

    redirect_to root_path
  end

  private
    def gym_params
      params.require(:gym).permit(:name, :description, :logo, barbells_attributes: [:_delete])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barbells_helper.rb
module BarbellsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/barbells/new.html.erb
<h2>Included barbells</h2>
<%= form_with model: [ @gym, @gym.barbells.build ] do |form| %>
  <p>
    <%= form.label :brand %><br>
    <%= form.text_field :brand %>
  </p>
  <p>
    <%= form.label :weight %><br>
    <%= form.number_field :weight %>kg
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/gyms/_form.html.erb
<%= form_with model: gym do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% gym.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% gym.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <h3>Please include the link of your gym's pic</h3>
  <div>
    <%= form.label :logo %><br>
    <%= form.text_field :logo %>
    <% gym.errors.full_messages_for(:logo).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gyms/edit.html.erb
<h1>Edit Gym</h1>

<%= render "form", gym: @gym %>

<h2>Is a barbell provvided:</h2>
<%= form_with model: [ @gym, @gym.barbells.build ] do |form| %>
  <p>
    <%= form.label :brand %><br>
    <%= form.text_field :brand %>
  </p>
  <p>
    <%= form.label :weight %><br>
    <%= form.number_field :weight %>kg
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/gyms/index.html.erb
<div class="banner" style="background-image: url(https://s3-us-west-2.amazonaws.com/issuewireassets/primg/14456/highest-quality-crossfit-equipment.jpg);">
  <div class="container">
    <h1>GYMExpress</h1>
    <p>Rent homegyms near you!</p>
    <p><%= link_to "Add your homegym", new_gym_path %></p>
  </div>
</div>

<div class="subtitle">
<h2>Our locations:</h2>
</div>




<% @gyms.each do |gym|%>
<div  class="card-product">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-product-infos">
    <h2><%= link_to gym.name, gym %></h2>
    <p><%= gym.description %></p>
  </div>
</div>
<%end%>

app/views/gyms/new.html.erb
<h1>Add your own homegym</h1>

<%= render "form", gym: @gym %>

app/views/gyms/show.html.erb
<div class="container container-gym">
  <%= image_tag @gym.logo %>
  <h2> <%= @gym.name%> </h2>
  <p> <%= @gym.description%> </p>
</div>

<div class="container container-equipment">
  <h3> Equipment </h3>

    <% @gym.barbells.each do |barbell| %>
      <div class="barbells">
          <p> Brand: <%= barbell.brand %></p>
          <p> Weight: <%= barbell.weight %>kg </p>
      </div>
    <% end %>
</div>

<div class="container container-options">
<%= link_to "HOME", gyms_path %>
<%= link_to "Modify entry", edit_gym_path(@gym) %>
<%= link_to "Delete", gym_path(@gym),
                  method: :delete,
                  data: { confirm: "Do you really want to get rid of this place?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gymexpress</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>